# Generated by Django 4.0.3 on 2022-06-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_socialperson_address_socialperson_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialperson',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
