# Generated by Django 4.0.3 on 2022-06-29 17:24

import Auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_socialperson_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialperson',
            name='back',
            field=models.ImageField(blank=True, default='', upload_to=Auth.models.user_directory_path),
        ),
    ]
