# Generated by Django 4.0.3 on 2022-06-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_socialperson_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialperson',
            name='job',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
